### ISSUE TITLE
Clasp doesn't seem to set errorlevel in windows

### ISSUE THREAD

**Issue by seeker1983** [google/clasp#1019]
Simple issue - it seems that the clasp doesn't set error code(%errorlevel% in windows in case of failure)
That's how it looks

d:\gas\internal>clasp push
/ Pushing files…Push failed. Errors:
GaxiosError: Syntax error: SyntaxError: Unexpected identifier 'en' line: 1 file: code.gs
    at Gaxios._request (C:\Users\Roman\AppData\Roaming\npm\node_modules\@google\clasp\node_modules\gaxios\build\src\gaxios.js:129:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuth2Client.requestAsync (C:\Users\Roman\AppData\Roaming\npm\node_modules\@google\clasp\node_modules\google-auth-library\build\src\auth\oauth2client.js:368:18)
    at async pushFiles (file:///C:/Users/Roman/AppData/Roaming/npm/node_modules/@google/clasp/build/src/files.js:296:17)
    at async Command.default (file:///C:/Users/Roman/AppData/Roaming/npm/node_modules/@google/clasp/build/src/commands/push.js:63:5)
    at async Command.parseAsync (C:\Users\Roman\AppData\Roaming\npm\node_modules\@google\clasp\node_modules\commander\lib\command.js:923:5)
    at async file:///C:/Users/Roman/AppData/Roaming/npm/node_modules/@google/clasp/build/src/index.js:361:9 {
  response: {
    config: {
      url: 'https://script.googleapis.com/v1/projects/18DaHJ_AzDi3FUy_KLgLrn3JlM2_JbZVtNtF2EfYkGULL_Zc5_rCRahb_/content',
      method: 'PUT',
      userAgentDirectives: [Array],
      paramsSerializer: [Function (anonymous)],
      data: [Object],
      headers: [Object],
      params: {},
      validateStatus: [Function (anonymous)],
      retry: true,
      body: '{...}'
  errors: [
    {
      message: "Syntax error: SyntaxError: Unexpected identifier 'en' line: 1 file: code.gs",
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
└─ appsscript.json
└─ code.js
Pushed 2 files.

d:\gas\internal>echo %errorlevel%
0

Is it not implemented?

**Comment by sqrrrl** [comment]
It is supposed to be setting the error code at https://github.com/google/clasp/blob/576250f8408f51b591aea3e398a6192cfcc1ee04/src/index.ts#L403 , but looks like the error isn't propagated from https://github.com/google/clasp/blob/576250f8408f51b591aea3e398a6192cfcc1ee04/src/files.ts#L388

Easiest fix is to rethrow the error in pushFiles()

**Comment by sqrrrl** [comment]
Should be fixed in 2.5.0
