### ISSUE TITLE
export typescript keyword isn't ignored on transpiling

### ISSUE THREAD

**Issue by nick-brainlabs** [google/clasp#263]
## Expected Behavior
`export const pi = 3.141592;`
in a typescript file to become:
`const pi = 3.141592;`
in gas.

## Actual Behavior
My app script has this instead:
```
exports.__esModule = true;
exports.pi = 3.141;
```
Which raises the following error:

`ReferenceError: "exports" is not defined. (line 1, file "src/foo")`

## Steps to Reproduce the Problem
1. make a typescript file with example from docs
2. `clasp push`
3. inspect code in app scripts

## Specifications

  - Node version (`node -v`): 10.7.0
  - Version (`clasp -v`): 1.5.0
  - OS (Mac/Linux/Windows): Mac

**Comment by nick-brainlabs** [comment]
This ticket is very similar to https://github.com/google/clasp/issues/262. The difference being if I'm getting the expected behaviour wrong should the current docs be more precise?

**Comment by grant** [comment]
Thanks for the report.
I'll have to update the docs or make `exports` not give an error.
In the meantime, don't use the `export` keyword.

**Comment by grant** [comment]
Apps Script doesn't support modules, and every identifier is global.

Would it be okay to just update the [TypeScript doc](https://github.com/google/clasp/blob/master/docs/typescript.md) to ask users to not use this keyword and close this issue?

**Comment by nick-brainlabs** [comment]
My use case for the export keyword is TDD with Jest. I think it depends on whether that's considered to be in scope or not.

**Comment by grant** [comment]
I'm going to make the expected behavior for 
```ts
export const pi = 3.1415;
```

to be

```js
exports.pi = 3.141592;
```

As that is the intent of using the `exports` keyword (and the output of the TypeScript compiler). I'm figuring a way around this issue https://github.com/Microsoft/TypeScript/issues/14351.

If you'd rather not have `exports.`, don't use the `export` keyword.

Let me know if there's anything wrong with the behavior above.

**Comment by grant** [comment]
Can you try installing the latest version of clasp `1.5.1`, and see if the behavior works?

**Comment by nick-brainlabs** [comment]
I've had a go and it's working as expected.

I'm getting errors whenever I had jest as a dependency which I wasn't getting the other day. It's happening with both `1.5.0` and `1.5.1`
```
clasp push
\ Pushing files.../usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:4503
            throw e;
            ^

Error: Debug Failure. Unexpected moduleResolution: false
    at Object.resolveModuleName (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:25746:30)
    at loader_1 (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:78454:78)
    at loadWithLocalCache (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:78321:42)
    at resolveModuleNamesWorker (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:78455:88)
    at resolveModuleNamesReusingOldState (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:78627:24)
    at processImportedModules (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:79804:35)
    at findSourceFile (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:79696:17)
    at /usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:79567:85
    at getSourceFileFromReferenceWorker (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:79534:34)
    at processSourceFile (/usr/local/lib/node_modules/@google/clasp/node_modules/typescript/lib/typescript.js:79567:13)
```

I appreciate this might be out of the scope of this issue though

**Comment by grant** [comment]
@nick-brainlabs Can you see if `1.5.2` has the error `Error: Debug Failure. Unexpected moduleResolution: false`?

Can you paste the error again with the source code to reproduce it?

**Comment by nick-brainlabs** [comment]
@grant `1.5.2` fixes it and jest is running fine. This is really exciting, thanks for looking into it!
