### ISSUE TITLE
Install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by whitecoop** [google/clasp#4]
After having an issue with the install on mac (#3), I gave my other machine a go.

I ran `npm i @google/clasp -g` per the installation instructions and got a `npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'` (full output below). I then ran ` sudo npm i @google/clasp -g` and got `npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/resolve-384a17c1' -> '/usr/lib/node_modules/@google/clasp/node_modules/resolve'` (full output also below).

---

Error output from `npm i @google/clasp -g`:
```
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ @google/clasp@1.0.5
  ├─┬ anymatch@1.3.2
  │ ├─┬ micromatch@2.3.11
  │ │ ├─┬ arr-diff@2.0.0
  │ │ │ └── arr-flatten@1.1.0
  │ │ ├── array-unique@0.2.1
  │ │ ├─┬ braces@1.8.5
  │ │ │ ├─┬ expand-range@1.8.2
  │ │ │ │ └─┬ fill-range@2.2.3
  │ │ │ │   ├── is-number@2.1.0
  │ │ │ │   ├─┬ isobject@2.1.0
  │ │ │ │   │ └── isarray@1.0.0
  │ │ │ │   ├─┬ randomatic@1.1.7
  │ │ │ │   │ ├─┬ is-number@3.0.0
  │ │ │ │   │ │ └── kind-of@3.2.2
  │ │ │ │   │ └── kind-of@4.0.0
  │ │ │ │   └── repeat-string@1.6.1
  │ │ │ ├── preserve@0.2.0
  │ │ │ └── repeat-element@1.1.2
  │ │ ├─┬ expand-brackets@0.1.5
  │ │ │ └── is-posix-bracket@0.1.1
  │ │ ├── extglob@0.3.2
  │ │ ├── filename-regex@2.0.1
  │ │ ├── is-extglob@1.0.0
  │ │ ├── is-glob@2.0.1
  │ │ ├─┬ kind-of@3.2.2
  │ │ │ └── is-buffer@1.1.6
  │ │ ├─┬ object.omit@2.0.1
  │ │ │ ├─┬ for-own@0.1.5
  │ │ │ │ └── for-in@1.0.2
  │ │ │ └── is-extendable@0.1.1
  │ │ ├─┬ parse-glob@3.0.4
  │ │ │ ├─┬ glob-base@0.3.0
  │ │ │ │ └── glob-parent@2.0.0
  │ │ │ └── is-dotfile@1.0.3
  │ │ └─┬ regex-cache@0.4.4
  │ │   └─┬ is-equal-shallow@0.1.3
  │ │     └── is-primitive@2.0.0
  │ └─┬ normalize-path@2.1.1
  │   └── remove-trailing-separator@1.1.0
  ├── cli-spinner@0.2.7
  ├── commander@2.13.0
  ├─┬ connect@3.6.5
  │ ├─┬ debug@2.6.9
  │ │ └── ms@2.0.0
  │ ├─┬ finalhandler@1.0.6
  │ │ ├── encodeurl@1.0.1
  │ │ ├── escape-html@1.0.3
  │ │ ├─┬ on-finished@2.3.0
  │ │ │ └── ee-first@1.1.1
  │ │ ├── statuses@1.3.1
  │ │ └── unpipe@1.0.0
  │ ├── parseurl@1.3.2
  │ └── utils-merge@1.0.1
  ├─┬ del@3.0.0
  │ ├─┬ globby@6.1.0
  │ │ ├─┬ array-union@1.0.2
  │ │ │ └── array-uniq@1.0.3
  │ │ ├─┬ glob@7.1.2
  │ │ │ ├── fs.realpath@1.0.0
  │ │ │ ├─┬ inflight@1.0.6
  │ │ │ │ └── wrappy@1.0.2
  │ │ │ ├── inherits@2.0.3
  │ │ │ ├── minimatch@3.0.4
  │ │ │ └── once@1.4.0
  │ │ ├── object-assign@4.1.1
  │ │ ├── pify@2.3.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├── is-path-cwd@1.0.0
  │ ├─┬ is-path-in-cwd@1.0.0
  │ │ └─┬ is-path-inside@1.0.1
  │ │   └── path-is-inside@1.0.2
  │ ├── p-map@1.2.0
  │ ├── pify@3.0.0
  │ └── rimraf@2.6.2
  ├─┬ dotf@1.0.3
  │ ├── jsonfile@3.0.1
  │ ├─┬ resolve-file@0.3.0
  │ │ ├─┬ cwd@0.10.0
  │ │ │ └─┬ find-pkg@0.1.2
  │ │ │   └─┬ find-file-up@0.1.3
  │ │ │     └─┬ resolve-dir@0.1.1
  │ │ │       ├─┬ expand-tilde@1.2.2
  │ │ │       │ └── os-homedir@1.0.2
  │ │ │       └─┬ global-modules@0.2.3
  │ │ │         ├─┬ global-prefix@0.1.5
  │ │ │         │ ├── ini@1.3.5
  │ │ │         │ └─┬ which@1.3.0
  │ │ │         │   └── isexe@2.0.0
  │ │ │         └── is-windows@0.2.0
  │ │ ├── expand-tilde@2.0.2
  │ │ ├── extend-shallow@2.0.1
  │ │ ├── fs-exists-sync@0.1.0
  │ │ ├─┬ homedir-polyfill@1.0.1
  │ │ │ └── parse-passwd@1.0.0
  │ │ ├─┬ lazy-cache@2.0.2
  │ │ │ └─┬ set-getter@0.1.0
  │ │ │   └── to-object-path@0.3.0
  │ │ └─┬ resolve@1.5.0
  │ │   └── path-parse@1.0.5
  │ └─┬ resolve-path@1.3.3
  │   ├─┬ http-errors@1.5.1
  │   │ └── setprototypeof@1.0.2
  │   └── path-is-absolute@1.0.1
  ├── find-parent-dir@0.3.0
  ├── fs@0.0.1-security
  ├─┬ googleapis@24.0.0
  │ ├─┬ async@2.6.0
  │ │ └── lodash@4.17.4
  │ ├─┬ google-auth-library@0.12.0
  │ │ ├─┬ gtoken@1.2.3
  │ │ │ ├─┬ google-p12-pem@0.1.2
  │ │ │ │ └── node-forge@0.7.1
  │ │ │ └── mime@1.6.0
  │ │ ├─┬ jws@3.1.4
  │ │ │ ├── base64url@2.0.0
  │ │ │ ├─┬ jwa@1.1.5
  │ │ │ │ ├── buffer-equal-constant-time@1.0.1
  │ │ │ │ └── ecdsa-sig-formatter@1.0.9
  │ │ │ └── safe-buffer@5.1.1
  │ │ ├── lodash.isstring@4.0.1
  │ │ ├── lodash.merge@4.6.0
  │ │ └─┬ request@2.83.0
  │ │   ├── aws-sign2@0.7.0
  │ │   ├── aws4@1.6.0
  │ │   ├── caseless@0.12.0
  │ │   ├─┬ combined-stream@1.0.5
  │ │   │ └── delayed-stream@1.0.0
  │ │   ├── extend@3.0.1
  │ │   ├── forever-agent@0.6.1
  │ │   ├─┬ form-data@2.3.1
  │ │   │ └── asynckit@0.4.0
  │ │   ├─┬ har-validator@5.0.3
  │ │   │ ├─┬ ajv@5.5.2
  │ │   │ │ ├── co@4.6.0
  │ │   │ │ ├── fast-deep-equal@1.0.0
  │ │   │ │ ├── fast-json-stable-stringify@2.0.0
  │ │   │ │ └── json-schema-traverse@0.3.1
  │ │   │ └── har-schema@2.0.0
  │ │   ├─┬ hawk@6.0.2
  │ │   │ ├── boom@4.3.1
  │ │   │ ├─┬ cryptiles@3.1.2
  │ │   │ │ └── boom@5.2.0
  │ │   │ ├── hoek@4.2.0
  │ │   │ └── sntp@2.1.0
  │ │   ├─┬ http-signature@1.2.0
  │ │   │ ├── assert-plus@1.0.0
  │ │   │ ├─┬ jsprim@1.4.1
  │ │   │ │ ├── extsprintf@1.3.0
  │ │   │ │ ├── json-schema@0.2.3
  │ │   │ │ └─┬ verror@1.10.0
  │ │   │ │   └── core-util-is@1.0.2
  │ │   │ └─┬ sshpk@1.13.1
  │ │   │   ├── asn1@0.2.3
  │ │   │   ├── bcrypt-pbkdf@1.0.1
  │ │   │   ├── dashdash@1.14.1
  │ │   │   ├── ecc-jsbn@0.1.1
  │ │   │   ├── getpass@0.1.7
  │ │   │   ├── jsbn@0.1.1
  │ │   │   └── tweetnacl@0.14.5
  │ │   ├── is-typedarray@1.0.0
  │ │   ├── isstream@0.1.2
  │ │   ├── json-stringify-safe@5.0.1
  │ │   ├─┬ mime-types@2.1.17
  │ │   │ └── mime-db@1.30.0
  │ │   ├── oauth-sign@0.8.2
  │ │   ├── performance-now@2.1.0
  │ │   ├── qs@6.5.1
  │ │   ├── stringstream@0.0.5
  │ │   ├─┬ tough-cookie@2.3.3
  │ │   │ └── punycode@1.4.1
  │ │   ├── tunnel-agent@0.6.0
  │ │   └── uuid@3.1.0
  │ └── string-template@1.0.0
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── open@0.0.5
  ├─┬ path@0.12.7
  │ ├── process@0.11.10
  │ └─┬ util@0.10.3
  │   └── inherits@2.0.1
  ├── pluralize@7.0.0
  ├── read-file@0.2.0
  ├─┬ read-multiple-files@1.1.1
  │ ├── graceful-fs@4.1.11
  │ ├── run-parallel@1.1.6
  │ └─┬ strip-bom@2.0.0
  │   └── is-utf8@0.2.1
  ├── readline@1.3.0
  ├─┬ recursive-readdir@2.2.1
  │ └─┬ minimatch@3.0.3
  │   └─┬ brace-expansion@1.1.8
  │     ├── balanced-match@1.0.0
  │     └── concat-map@0.0.1
  ├── split-lines@1.1.0
  └─┬ url@0.11.0
    ├── punycode@1.3.2
    └── querystring@0.2.0

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "@google/clasp" "-g"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/whitecoop/npm-debug.log
```

Error output from `sudo npm i @google/clasp -g`:
```
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "@google/clasp" "-g"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/resolve-384a17c1
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/resolve-384a17c1' -> '/usr/lib/node_modules/@google/clasp/node_modules/resolve'
npm ERR!     at destStatted (/usr/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:264:29npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/resolve-384a17c1' -> '/usr/lib/node_modules/@google/clasp/node_modules/resolve'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/resolve-384a17c1' -> '/usr/lib/node_modules/@google/clasp/node_modules/resolve'
npm ERR!     at destStatted (/usr/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:264:29npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/resolve-384a17c1' -> '/usr/lib/node_modules/@google/clasp/node_modules/resolve'
npm ERR!     at Error (native) parent: '@google/clasp' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/whitecoop/npm-debug.log
npm ERR! code 1
```

Here's a gist with the full contents of `npm-debug.log` (which, based on the numbering in the file, I'm assuming is just from the `sudo npm i @google/clasp -g` command): https://gist.github.com/whitecoop/75531aa876f5437b6c0c61e188a61f04

**Comment by grant** [comment]
It looks like you don't have permission to the folder (`npm WARN checkPermissions Missing write access to /usr/lib/node_modules`)

Have you installed other npm modules before without error?

Please follow npm's guide:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

If that doesn't work, maybe try giving permission to the folder:
`chmod 777 /usr/lib/node_modules`

**Comment by whitecoop** [comment]
> Have you installed other npm modules before without error?

I had, but sometimes they needed `sudo` to complete.

> Please follow npm's guide:
> https://docs.npmjs.com/getting-started/fixing-npm-permissions

I followed the guide (I did the [install nvm option](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-one-reinstall-with-a-node-version-manager)) and that cleared it up. Clasp installed successfully. 👍
