### ISSUE TITLE
Offline Error Messages

### ISSUE THREAD

**Issue by labnol** [google/clasp#41]
If a user executes the clasp push command while the network is silently down, the following errors are shown.  Can the script check for network connection before proceeding?

```
Push failed. Errors:
(node:67970) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /Users/labnol/digitalinspiration/node_modules/@google/clasp/index.js:587:46
    at /Users/labnol/digitalinspiration/node_modules/google-auth-library/build/src/auth/oauth2client.js:396:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:67970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:67970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by grant** [comment]
To handle this, we could add an [`is-online`](https://github.com/sindresorhus/is-online) check before every network call.

**Comment by arjun-rao** [comment]
@grant I guess this issue can be closed now.
