### ISSUE TITLE
gcp-metadata module not found

### ISSUE THREAD

**Issue by caseyduquettesc** [google/clasp#45]
## Expected Behavior
no error?

## Actual Behavior
Module not found error

```
Error: Cannot find module 'gcp-metadata'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/google-auth-library/build/src/auth/googleauth.js:55:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

## Steps to Reproduce the Problem

  1. Ran `npm install -g @google/clasp`
  1. Any clasp command issues same error

## Specifications

  - Node version (`node -v`): 9.4
  - Version (`npm list -g | grep clasp`): 1.1.1
  - OS (Mac/Linux/Windows): mac 10.13

**Comment by grant** [comment]
Looking at:
`/usr/local/lib/node_modules/@google/clasp/node_modules/google-auth-library/build/src/auth/googleauth.js:55:19`

It looks like an issue with `google-auth-library`. Can you see if there is an issue there?

**Comment by caseyduquettesc** [comment]
For the record it was easily solved by installing gcp-metadata, but it wasn't mentioned anywhere in the docs.

**Comment by grant** [comment]
Do you still see the error?

**Comment by caseyduquettesc** [comment]
No, just wanted others to know that there's an extra step involved in the installation.

**Comment by grant** [comment]
I don't think `gcp-metadata` is required for this module. It should work if you don't install it.

**Comment by caseyduquettesc** [comment]
It isn't required for this, but it's required by one of this package's dependencies. Regardless, it was just fixed in the google-auth-library

https://github.com/google/google-auth-library-nodejs/commit/3533dd9e70582dd802cda75c7c77d1d99090d5a5

**Comment by grant** [comment]
We should fix the problem upstream rather than every single dependency.
