### ISSUE TITLE
clasp push returning 500 errors

### ISSUE THREAD

**Issue by ricotheque** [google/clasp#686]
## Expected Behavior

When I run `clasp push`, changes I made on local should be pushed to the corresponding Google Script project.

## Actual Behavior

When I run `clasp push`, several 500 errors appear. The files I'm trying to push aren't updated on the cloud.

```
\ Pushing files...Push failed. Errors:
{ Error: Internal error encountered.
    at Gaxios.request (/usr/local/lib/node_modules/@google/clasp/node_modules/gaxios/build/src/gaxios.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   { config:
      { url:
         'https://script.googleapis.com/v1/projects/[SCRIPT_ID]/content',
        method: 'PUT',
        paramsSerializer: [Function],
        data: [Object],
        headers: [Object],
        params: [Object: null prototype] {},
        validateStatus: [Function],
        retry: true,
        body:
         '{"scriptId":"[SCRIPT_ID]","files":[{"name":"Code","type":"SERVER_JS","source":"[CODE]"}]}',
        responseType: 'json',
        retryConfig: [Object] },
     data: { error: [Object] },
     headers:
      { 'alt-svc': 'quic=":443"; ma=2592000; v="46,43,39"',
        'cache-control': 'private',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Thu, 15 Aug 2019 07:42:22 GMT',
        server: 'ESF',
        'transfer-encoding': 'chunked',
        vary: 'Origin, X-Origin, Referer',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '0' },
     status: 500,
     statusText: 'Internal Server Error' },
  config:
   { url:
      'https://script.googleapis.com/v1/projects/[SCRIPT_ID]/content',
     method: 'PUT',
     paramsSerializer: [Function],
     data:
      { scriptId: '[SCRIPT_ID]',
        files: [Array] },
     headers:
      { 'Accept-Encoding': 'gzip',
        'User-Agent': 'google-api-nodejs-client/2.0.4 (gzip)',
        Authorization:
         'Bearer [BEARER_TOKEN]',
        'Content-Type': 'application/json',
        Accept: 'application/json' },
     params: [Object: null prototype] {},
     validateStatus: [Function],
     retry: true,
     body:
      '{"scriptId":"[SCRIPT_ID]","files":[{"name":"Code","type":"SERVER_JS","source":"[CODE]"}]}',
     responseType: 'json',
     retryConfig:
      { currentRetryAttempt: 3,
        retry: 3,
        retryDelay: 100,
        httpMethodsToRetry: [Array],
        noResponseRetries: 2,
        statusCodesToRetry: [Array] } },
  code: 500,
  errors:
   [ { message: 'Internal error encountered.',
       domain: 'global',
       reason: 'backendError' } ] }
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
└─ [FILENAME]
Pushed 14 files.
```

## Steps to Reproduce the Problem

1. Use `clasp push` before with no problem
2. Encounter error described above
3. Update clasp with `sudo npm i @google/clasp -g`
4. Attempt `clasp push` again
5. Still get the same errors

## Specifications

- Node version (`node -v`): v10.16.2
- Version (`clasp -v`): 2.2.1
- OS (Mac/Linux/Windows): macOS 10.14.6

**Comment by ricotheque** [comment]
@grant thanks for taking a look.

The issue resolved itself, after I:

1. Restarted my laptop
2. Reopened Terminal and returned to the Project directory
3. Ran `clasp pull`
4. Ran `clasp push` and no longer encountered errors.

Given this, I'm closing the issue.
