### ISSUE TITLE
"unable to get local issuer certificate" error for some clasp commands

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#719]
## Expected Behavior

Depends on the `clasp` command being called. Details below.

## Actual Behavior

I am getting errors when running some `clasp` commands. I am able to `clone`, `push` and `pull` just fine but other commands yield an error.

I don't know if it is relevant but, while `clone`, `pull`, `push` all work, after they are done they sit waiting for a 30+ seconds before returning the prompt. I don't know what it is doing or why it takes so long.

## Steps to Reproduce the Problem

- `clasp list` results in this error:

    > ```
    > request to https://www.googleapis.com/drive/v3/files?pageSize=50&q=mimeType%3D%22application%2Fvnd.google-apps.script%22 failed, reason: unable to get local issuer certificate
    > ```

- `clasp apis list` shows the `# Currently enabled APIs:` but right when it starts to `# List of available APIs:` it shows this error:

    > ```
    > # List of available APIs:
    > (node:10608) UnhandledPromiseRejectionWarning: FetchError: request to https://www.googleapis.com/discovery/v1/apis?preferred=true failed, reason: unable to get local issuer certificate
    >     at ClientRequest.<anonymous> (C:\Users\nigaman\AppData\Roaming\npm\node_modules\@google\clasp\node_modules\node-fetch\lib\index.js:1455:11)
    >     at ClientRequest.emit (events.js:198:13)
    >     at TLSSocket.socketErrorListener (_http_client.js:392:9)
    >     at TLSSocket.emit (events.js:198:13)
    >     at emitErrorNT (internal/streams/destroy.js:91:8)
    >     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    >     at process._tickCallback (internal/process/next_tick.js:63:19)
    > (node:10608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    > (node:10608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    > ```

## Specifications

- Node version: **v10.16.3**
- Clasp version: **2.3.0**
- OS: **Windows 10**
- Enterprise G-Suite

**Comment by PopGoesTheWza** [comment]
@imthenachoman independently of your certificate/TLS issue, the error log points at a hole in error handling. Can you produce a PR for that aspect?

**Comment by imthenachoman** [comment]
I'm still somewhat green with how GitHub works. By PR do you mean fork the code, fix it, and then submit a pull request? I can't do any kind of debugging/development for CLASP from work. I can try to look from home but it'll be a while before I can dig through the code. I've never looked through it before and I'm not great with TypeScript.

**Comment by imthenachoman** [comment]
I don't know why I didn't see this before but I just tried a `clasp list` and got this error -- it has more detail then I saw before.

   > ```
   > request to https://www.googleapis.com/drive/v3/files?pageSize=50&q=mimeType%3D%22application%2Fvnd.google-apps.script%22 failed, reason: unable to get local issuer certificate
   > ```

When I go to https://www.googleapis.com/drive/v3/files?pageSize=50&q=mimeType%3D%22application%2Fvnd.google-apps.script%22, I see this:

   > ```
   > {
   >  "error": {
   >   "errors": [
   >    {
   >     "domain": "usageLimits",
   >     "reason": "dailyLimitExceededUnreg",
   >     "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
   >     "extendedHelp": "https://code.google.com/apis/console"
   >    }
   >   ],
   >   "code": 403,
   >   "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
   >  }
   > }
   > ```

I have done `clasp login` and can `push` and `pull` just fine.

**Comment by PopGoesTheWza** [comment]
@imthenachoman is the issue permanent? Your last message seems to imply you are experiencing a quota issue (<https://developers.google.com/apps-script/guides/services/quotas>)

As for the messy `UnhandledPromiseRejectionWarning` error, I see several `await` with no `try`...`catch` wrapping to properly handle failure when interracting with the Google APIs.

If we get feedback from some owner like @grant or @sqrrrl , I can create a PR to correctly handle such errors.

**Comment by imthenachoman** [comment]
@PopGoesTheWza Yes. I don't think it is a quota issue since it happens every time. The error says "for Unauthenticated Use". I don't know how the `clasp` code works but I assume when I run `clasp list` it would make an authenticated call...

**Comment by imthenachoman** [comment]
Just checking if there is any update to this?

**Comment by imthenachoman** [comment]
@sqrrrl Was this issue fixed?

**Comment by sqrrrl** [comment]
Not explicitly, but not reproducible at the moment and given the age, likely not relevant any more. Certificate errors like that tend to be very system dependent and usually due to outdated root certificate list. IIRC there were some root CA changes around 2018/2019 and the fact that some APIs worked and others didn't fits with that. 

In any case, don't expect this to be an issue any more, but if you are seeing issues re-open the issue.
