### ISSUE TITLE
Command  "clasp version"  emits TypeError

### ISSUE THREAD

**Issue by kenyodev** [google/clasp#748]
## Expected Behavior
Prints out version information

## Actual Behavior
Emits TypeError

```
kenyo@Kens-MacBook-Pro mc % npm install -g @google/clasp
/Users/kenyo/.nvm/versions/node/v10.0.0/bin/clasp -> /Users/kenyo/.nvm/versions/node/v10.0.0/lib/node_modules/@google/clasp/src/index.js
npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @google/clasp@2.3.0
added 162 packages in 12.356s
kenyo@Kens-MacBook-Pro mc % clasp
/Users/kenyo/.nvm/versions/node/v10.0.0/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7
const { access, chmod, unlink } = graceful_fs_1.promises;
        ^

TypeError: Cannot destructure property `access` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/kenyo/.nvm/versions/node/v10.0.0/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7:49)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kenyo/.nvm/versions/node/v10.0.0/lib/node_modules/@google/clasp/src/dotfile.js:24:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
kenyo@Kens-MacBook-Pro mc %
```

## Steps to Reproduce the Problem

1. Install clasp by `npm install -g @google/clasp`
2. Execute a command `clasp version`

## Specifications

- Node version (`node -v10.0.0`):
- Version (`clasp -v2.3.0`):
- OS (Mac Catalina):

**Comment by andybrewer** [comment]
Similar issue for me running `clasp login`

```
clasp login
/Users/ever/.nvm/versions/node/v8.5.0/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7
const { access, chmod, unlink } = graceful_fs_1.promises;
                                               ^

TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/Users/ever/.nvm/versions/node/v8.5.0/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7:48)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ever/.nvm/versions/node/v8.5.0/lib/node_modules/@google/clasp/src/dotfile.js:24:12)
    at Module._compile (module.js:624:30)
```

# Steps to Reproduce the Problem
Install clasp by `npm install -g @google/clasp`
Execute a command `clasp login`

# Specifications
Node version (node -v 8.5.0)
Version (clasp -v 2.3.0)
OS (Mac Mojave)

**Comment by kalkov** [comment]
+1

**Comment by kalkov** [comment]
Quick fix - lock `dotf` version in your `package.json` file

```json
"dotf": "1.4.2"
```

**Comment by PopGoesTheWza** [comment]
@kenyodev @andybrewer can you share the output of `npm list -g dotf graceful-fs`?

Also supported NodeJS version should be ">= 10.3.0"

**Comment by rodrigoscdc** [comment]
Similar Issue to me, after that I update my clasp package

I ran `npm install -g @google/clasp`

`clasp -v`
I got this error

```
/usr/local/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7
const { access, chmod, unlink } = graceful_fs_1.promises;
        ^

TypeError: Cannot destructure property `access` of 'undefined' or 'null'.
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7:49)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/src/dotfile.js:24:12)
    at Module._compile (module.js:662:30)
```

I tried to include the `"dotf": "1.4.2"` like @kalkov suggest but didn't work.


### NPM Version
`npm -v` = 5.6.0

### Node Version
`node -v` = v9.7.1
### OS mac El Capitan
10.11.6

### Result for NPM LIST
`npm list -g dtof graceful-fs`
```/usr/local/lib
├─┬ @google/clasp@2.3.0
│ ├─┬ dotf@1.5.0 
│ │ ├── graceful-fs@4.2.3 
│ │ └─┬ jsonfile@6.0.1
│ │   └── graceful-fs@4.2.3  deduped
│ ├─┬ fs-extra@8.1.0
│ │ ├── graceful-fs@4.2.3  deduped
│ │ └─┬ jsonfile@4.0.0
│ │   └── graceful-fs@4.2.3  deduped
│ └─┬ nyc@14.1.1
│   ├─┬ caching-transform@3.0.2
│   │ ├─┬ package-hash@3.0.0
│   │ │ └── graceful-fs@4.2.3  deduped
│   │ └─┬ write-file-atomic@2.4.3
│   │   └── graceful-fs@4.2.3  deduped
│   ├─┬ cp-file@6.2.0
│   │ └── graceful-fs@4.2.3  deduped
│   └─┬ test-exclude@5.2.3
│     └─┬ read-pkg-up@4.0.0
│       └─┬ read-pkg@3.0.0
│         └─┬ load-json-file@4.0.0
│           └── graceful-fs@4.2.3  deduped
├─┬ dotf@1.4.2 
│ └─┬ jsonfile@5.0.0
│   └── graceful-fs@4.2.3 
├── graceful-fs@4.2.3 
└─┬ npm@5.6.0
  ├─┬ @google/clasp@1.3.0
  │ ├─┬ dotf@1.4.2 
  │ │ └─┬ jsonfile@5.0.0
  │ │   └── graceful-fs@4.1.11  deduped
  │ └─┬ read-multiple-files@1.1.1
  │   └── graceful-fs@4.1.11  deduped
  ├─┬ bin-links@1.1.0
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ cacache@10.0.1
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ cmd-shim@2.0.2
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ fs-vacuum@1.2.10
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ fs-write-stream-atomic@1.0.10
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ gentle-fs@2.0.1
  │ └── graceful-fs@4.1.11  deduped
  ├── graceful-fs@4.1.11 
  ├─┬ libnpx@9.7.1
  │ └─┬ yargs@8.0.2
  │   └─┬ read-pkg-up@2.0.0
  │     └─┬ read-pkg@2.0.0
  │       └─┬ load-json-file@2.0.0
  │         └── graceful-fs@4.1.11  deduped
  ├─┬ npm-lifecycle@2.0.0
  │ ├── graceful-fs@4.1.11  deduped
  │ └─┬ node-gyp@3.6.2
  │   ├─┬ fstream@1.0.11
  │   │ └── graceful-fs@4.1.11  deduped
  │   └── graceful-fs@4.1.11  deduped
  ├─┬ npm-profile@2.0.5
  │ └─┬ make-fetch-happen@2.5.0
  │   └─┬ cacache@9.3.0
  │     └── graceful-fs@4.1.11  deduped
  ├─┬ npm-registry-client@8.5.0
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ read-cmd-shim@1.0.1
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ read-installed@4.0.3
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ read-package-json@2.0.12
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ readdir-scoped-modules@1.0.2
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ sha@2.0.1
  │ └── graceful-fs@4.1.11  deduped
  ├─┬ standard@6.0.8
  │ └─┬ eslint@2.2.0
  │   └─┬ file-entry-cache@1.3.1
  │     └─┬ flat-cache@1.3.4
  │       └── graceful-fs@4.1.11  deduped
  ├─┬ tap@10.7.3
  │ └─┬ nyc@11.9.0
  │   ├─┬ caching-transform@1.0.1
  │   │ └─┬ write-file-atomic@1.3.4
  │   │   └── graceful-fs@4.1.11 
  │   └─┬ test-exclude@4.2.1
  │     └─┬ read-pkg-up@1.0.1
  │       └─┬ read-pkg@1.1.0
  │         ├─┬ load-json-file@1.1.0
  │         │ └── graceful-fs@4.1.11  deduped
  │         └─┬ path-type@1.1.0
  │           └── graceful-fs@4.1.11  deduped
  ├─┬ update-notifier@2.3.0
  │ └─┬ configstore@3.1.1
  │   └── graceful-fs@4.1.11  deduped
  └─┬ write-file-atomic@2.1.0
    └── graceful-fs@4.1.11  deduped
```

**Comment by pipriles** [comment]
I am also facing this issue after doing `sudo npm install -g @google/clasp`:
This is the output when I run `clasp`:

```
/usr/local/lib/node_modules/@google/clasp/node_modules/dotf/lib/index.js:7
const { access, chmod, unlink } = graceful_fs_1.promises;
        ^

TypeError: Cannot destructure property `access` of 'undefined' or 'null'.
```

**Comment by kagawish** [comment]
I was using node version `v8.x`, upgrading to node `v12.x `which is the LTS, it is working now, so I think not even necessary to update to `v14.x`

**Comment by PopGoesTheWza** [comment]
Can you test with the #791 unofficial release?

```shell
npm uninstall -g @google/clasp && npm install -g forked-clasp
clasp --version
# should be 2.4.0 or more
```

**Comment by kenyodev** [comment]
@PopGoesTheWza 

Sorry I haven't checked this issue for a while.
The error went away after updating the node version to a higher one.

> Also supported NodeJS version should be ">= 10.3.0"

This was the solution for me.

**Comment by dacgray** [comment]
Same as @kenyodev 

Needed to update node.
