### ISSUE TITLE
clasp should not try to push if GaxiosError fails because of SyntaxErrors

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#811]
## Expected Behavior

`clasp` should not try to push the code if `GaxiosError` fails because of `SyntaxErrors`

## Actual Behavior

`clasp` spits out that GaxiosError failed because of SyntaxErrors and then pushes the code.

Below we can see that there are syntax errors, yet it still pushed. I would think/expect that if there are syntax errors then it would not try to push -- no point.

```
nacho@machine folder % clasp push
/ Pushing files...Push failed. Errors:
GaxiosError: Syntax error: SyntaxError: Invalid or unexpected token line: 5 file: code.gs
    at Gaxios._request (/usr/local/lib/node_modules/@google/clasp/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async OAuth2Client.requestAsync (/usr/local/lib/node_modules/@google/clasp/node_modules/google-auth-library/build/src/auth/oauth2client.js:350:18) {
  response: {
    config: {
      url: '...',
      method: 'PUT',
      paramsSerializer: [Function (anonymous)],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function (anonymous)],
      retry: true,
      body: `{...}`,
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Fri, 02 Oct 2020 15:36:55 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: '...'
    }
  },
  config: {
    url: '...',
    method: 'PUT',
    paramsSerializer: [Function (anonymous)],
    data: {
      scriptId: '...',
      files: [Array]
    },
    headers: {
      'x-goog-api-client': 'gdcl/3.2.2 gl-node/14.12.0 auth/5.10.1',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/3.2.2 (gzip)',
      Authorization: 'Bearer ...',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function (anonymous)],
    retry: true,
    body: `{...}`,
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      message: 'Syntax error: SyntaxError: Invalid or unexpected token line: 5 file: code.gs',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
└─ appsscript.json
└─ code.js

Pushed 2 files.
```

## Steps to Reproduce the Problem

1. write invalid JS code
1. push it

## Specifications

- Node version (`node -v`): 14.12.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): MacOS 10.15

**Comment by fmpanelli** [comment]
I have the same problem.

Additionally, I cannot find the pushed version of the scripts at script.google.com.

It seems the scripts are not really pushed anywhere.

**Comment by Nu11u5** [comment]
The GaxiosError is actually a response from script.google.com.  After pushing the file GAS will perform a syntax check and reject any invalid pushes.

**Comment by imthenachoman** [comment]
Isn't the GaxiosError check done **before** the push?

**Comment by Nu11u5** [comment]
> Isn't the GaxiosError check done **before** the push?

Well the HTTP response is right there in the error object.

**Comment by imthenachoman** [comment]
I will show myself the door. 

Sorry!
