### ISSUE TITLE
Suppress GaxiosError object dump

### ISSUE THREAD

**Issue by Nu11u5** [google/clasp#827]
## Details

When `clasp push` is run with project files containing invalid syntax, a stack trace is output to stderr.  The stack trace contains the full error object including the HTTP request and response objects, headers, authorization tokens, and the appsscript file content itself (which can be quite lengthy).  This is extremely verbose, leaks credentials to the terminal, and causes performance issues in some terminals (such as the VSCode terminal).

## Proposed Behavior

If clasp receives an error, it only outputs the general error message information.  If verbose error information is needed, an additional command parameter could be used to output the stack trace and full error object to stderr.

## Specifications

- Node version: 12.16.3
- Version: 2.3.0
- OS: Windows 10 build 18363.1316

**Comment by Nu11u5** [comment]
As a workaround, stderr can be redirected to null, but this also hides the general error information.

Windows: `clasp push 2> nul`
Linux: `clasp push 2> /dev/null`

**Comment by Nu11u5** [comment]
### Example error (anonymized)

``` text
Push failed. Errors:
GaxiosError: Syntax error: SyntaxError: ...
    at Gaxios._request (...\npm\node_modules\@google\clasp\node_modules\gaxios\build\src\gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OAuth2Client.requestAsync (...\npm\node_modules\@google\clasp\node_modules\google-auth-library\build\src\auth\oauth2client.js:349:18)
```

``` javascript
{
  response: {
    config: {
      url: '...',
      method: 'PUT',
      paramsSerializer: [Function],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      body: '{...}',                            //// Multiline text including the appsscript file content, very long ////
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': '...',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Thu, 04 Feb 2021 21:23:57 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'https://script.googleapis.com/v1/projects/...'
    }
  },
  config: {
    url: 'https://script.googleapis.com/v1/projects/...',
    method: 'PUT',
    paramsSerializer: [Function],
    data: {
      scriptId: '...',
      files: [Array]
    },
    headers: {
      'x-goog-api-client': 'gdcl/3.2.0 gl-node/12.16.3 auth/5.7.0',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/3.2.0 (gzip)',
      Authorization: 'Bearer ...',              //// OAuth bearer token is leaked here ////
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    body: '{...}',                              //// Multiline text including the appsscript file content, very long ////
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      message: 'Syntax error: SyntaxError: ...',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```

**Comment by PopGoesTheWza** [comment]
@Nu11u5 can you make a PR for this?

**Comment by PopGoesTheWza** [comment]
@Nu11u5 Just to be sure the issue still exist, can you try replacing `@google/clasp` 2.3.0 with `forked-clasp` which is more advanced?

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```
