### ISSUE TITLE
Clasp login fails: "Error retrieving access token..."

### ISSUE THREAD

**Issue by maulikpipaliya** [google/clasp#912]
## Expected Behavior
Login is expected to be functional via browser.

## Actual Behavior
After logging in from the browser, it's not able to get the access token and produces the below error

```Error retrieving access token: FetchError: request to https://oauth2.googleapis.com/token failed, reason: read ETIMEDOUT
Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/usr/local/lib/node_modules/@google/clasp/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/usr/local/lib/node_modules/@google/clasp/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:510:26)
    at Request.emit (node:events:390:28)
    at Timeout.retry (/usr/local/lib/node_modules/@google/clasp/node_modules/got/dist/source/core/index.js:1270:30)
    at Timeout.retry (/usr/local/lib/node_modules/@google/clasp/node_modules/wtfnode/index.js:197:27)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```

## Specifications

- Node version (`node -v`): v16.13.2
- Version (`clasp -v`): 2.4.1
- OS (Mac/Linux/Windows): Mac

**Comment by kenkku** [comment]
I'm experiencing the same, #909

**Comment by sqrrrl** [comment]
Auth code has been reworked in 3.x + the issue in #909 was also fixed. Marking as fixed.
